### ISSUE TITLE
add docs to mvt api schemas

### ISSUE THREAD

**Issue by sofiasedlova** [1712n/dn-institute#11]

**Comment by marina-chibizova** [comment]
I'm not sure what you mean by docs, but I was planning to add some explanatory content there. Generated a [draft](https://docs.google.com/document/d/12rsfyvz4Cl-bS7_rWCEx5K0DBplqEzJ3g03Ul4WeMt8/edit?usp=sharing). If you meant more technical/financial docs, I'll just open a separate issue for my thing

**Comment by sofiasedlova** [comment]
I want to add missing `description` for each field within the object schemas

```
{
      "description": "",
      "name": "side",
      "type": "string"
}

**Comment by marina-chibizova** [comment]
got it, then it's not it
