### ISSUE TITLE
Add first Market Health article

### ISSUE THREAD

**Issue by sofiasedlova** [1712n/dn-institute#203]
- add `article-name.md` file with the article text to `content/market-health`
- add images to `content/market-health/img/article-name`
- name images properly and insert them into .md file
- create PR
- assign @sofiasedlova to review

**Comment by sofiasedlova** [comment]
@danisztls hey! our blog posts will normally include many images with technical charts. can we have a gallery view of them?

**Comment by danisztls** [comment]
@sofiasedlova Sure. Will implement this.

https://github.com/1712n/dn-institute/issues/204
