### ISSUE TITLE
Implement gallery view on posts

### ISSUE THREAD

**Issue by danisztls** [1712n/dn-institute#204]
Requested by https://github.com/1712n/dn-institute/issues/203#issuecomment-1670496658

**Comment by sofiasedlova** [comment]
hey, the team has prepared a [report](https://github.com/1712n/dn-institute/pull/207/files). could the galley view be possible with this publication?

**Comment by danisztls** [comment]
@sofiasedlova Are you aiming to publish it today? I can try to do it today.

**Comment by sofiasedlova** [comment]
will be good to have by Monday

**Comment by marina-chibizova** [comment]
@danisztls just a reminder about a [`draft: true`](https://github.dev/1712n/dn-institute)

**Comment by sofiasedlova** [comment]
@danisztls just a kind reminder, merci

**Comment by danisztls** [comment]
@marina-chibizova @sofiasedlova  Sorry. There are some issues which I'm working on. I prepped it for release in #211. Will fix the issues via follow up PRs.

**Comment by danisztls** [comment]
BTW @sofiasedlova by gallery you mean fully featured gallery like [this](https://photoswipe.com/) or just lightbox like in [Inca.digital](https://inca.digital/intelligence/how-russians-use-tether/)?

**Comment by sofiasedlova** [comment]
I think I misled you by calling what I want from the publication images a "gallery view". It's rather a horizontal [carousel](https://stackoverflow.com/questions/21905049/how-to-create-a-horizontal-carousel-view-in-android) that is easy to swipe. Let me know if that makes things more complicated on your side.

**Comment by danisztls** [comment]
> Let me know if that makes things more complicated on your side.

I will use a library, probably [LightGallery.js](https://www.lightgalleryjs.com/) or [PhotoSwipe](https://photoswipe.com/). Features provided by one of those are fine to implement.

> It's rather a horizontal [carousel](https://stackoverflow.com/questions/21905049/how-to-create-a-horizontal-carousel-view-in-android) that is easy to swipe.

@sofiasedlova Like the view that opens when clicking on any of the images on top of this [page](https://photoswipe.com/)?

**Comment by sofiasedlova** [comment]
> Like the view that opens when clicking on any of the images on top of this [page](https://photoswipe.com/)?

Yep
