### ISSUE TITLE
Wash Trading Detection

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/dn-institute#240]
> Wash trading is a process whereby a trader buys and sells a security for the express purpose of feeding misleading information to the market. In some situations, wash trades are executed by a trader and a broker who are colluding with each other, and other times wash trades are executed by investors acting as both the buyer and the seller of the security.

_[Investopedia](https://www.investopedia.com/terms/w/washtrading.asp)_

In the crypto industry, wash trading is a common occurrence, as many traders equate high trading volumes to healthy market liquidity. Trading venues and crypto projects are complacent and often collude with each other to generate fake trades that cost little to place and execute. You can find more technical details on wash trading techniques in [this YouTube video](https://www.youtube.com/watch?v=I-Um62NPm0A).

Please comment below with ideas on detecting wash trading based on a [stream of executed trades](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#trade-streams). More specifically, describe an algorithm you would use to create a metric capable of measuring wash trading in a given market pair volume. Feel free to support your ideas by adding references, datasets, graphs, and code. Comments with the best ideas will be hidden to allow others to participate. Multiple submission awards are available.

Many of the previous challenge participants focused on investigative approaches that involved manual analysis of specific cases of wash trading. This, however, is an engineering challenge, requiring successful submissions to include an algorithm, supported by references, datasets, graphs, and/or code. We have more than enough of ingenious ideas on how it can be done, but no solid plans of how to implement it using real-time streaming data.

**Comment by marina-chibizova** [comment]
Big thanks to all challenge participants! We've honed our methodology & metrics with the help of a brilliant team member hired from the challenge program.
Now, we're on the lookout for any valuable contributions to our Market Manipulation Wiki (in a form of market manipulation report, documentation, fixes, metrics suggestions, etc)  - check out the latest [bounty](https://github.com/1712n/dn-institute/issues/277)!
