### ISSUE TITLE
Twitter Home Timeline Scraper

### ISSUE THREAD

**Issue by Lavriz** [1712n/dn-institute#271]
## Your task
The goal of this challenge is to create a scraper for Twitter home "for you" timeline. We are interested in capturing relevant to us (according to Twitter recommendation engine) tweets / liked tweets / retweets. 
### Overview
The scraper will be deployed as a scheduled function that periodically checks timeline updates and sends new tweets to a MongoDB collection. Avoid Twitter's official API, but feel free to leverage their front-end GraphQL API or other reliable ways of obtaining the data. Please keep in mind that the submissions will be evaluated based on the combination of cost/efficiency, security, and stability.

### Data Schema

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "timestamp": {
      "type": "number",
      "description": "Unix epoch message timestamp"
    },
    "message": {
      "type": "object",
      "properties": {
        "text": { "type": "string" },
        "id": { "type": "string", "description": "Message ID" },
        "language": {
          "type": "string",
          "description": "Language of the Message"
        },
        "enrichment": {
          "$ref": "./enrichment_fields.json"
        },
        "media": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": { "type": "string", "enum": ["image", "audio", "video"] },
              "id": { "type": "string" },
              "title": { "type": "string" },
              "file_name": { "type": "string" },
              "url": {
                "type": "string",
                "description": "URL of the media file"
              }
            }
          }
        }
      },
      "required": ["text", "id"]
    },
    "user": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "id": { "type": "string" }
      },
      "description": "Sender of the Message"
    },
    "geo_coords": {
      "$ref": "https://geojson.org/schema/GeoJSON.json"
    },
    "source": {
      "type": "object",
      "properties": {
        "platform": {
          "type": "string",
          "description": "Telegram/Twitter/Reddit"
        },
        "channel": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "Name of the message source, such as a Telegram channel"
            },
            "id": { "type": "string" }
          }
        },
        "referenced_post": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "description": "URL link of the referenced post"
            },
            "id": { "type": "string" }
          }
        },
        "source_specific_fields": {
          "type": "object",
          "additionalProperties": true,
          "description": "Extra source-specific fields"
        }
      },
      "required": ["platform"]
    }
  },
  "required": ["timestamp", "message", "user", "source"]
}
```

## Submission

To participate, submit a pull request with your solution, along with a  .json with sample data, and request a review from @jalmonter. Expanding the pull request description with your methodology can help us better understand your reasoning and evaluate your submission faster.

---
🎉 @Hjklvfr submitted the winning pull request and claimed the bounty!

**Comment by Hjklvfr** [comment]
Where I can find ./enrichment_fields.json?

**Comment by Lavriz** [comment]
@Hjklvfr it's an external schema which you don't need here

**Comment by Hjklvfr** [comment]
@jalmonter I committed the solution

**Comment by Hjklvfr** [comment]
@Lavriz Did I do everything right?  I would like to receive feedback

**Comment by Lavriz** [comment]
> @Lavriz Did I do everything right?  I would like to receive feedback

@Hjklvfr 
@jalmonter reviewed your PR. As soon as you reply to comments in case you're still interested, we will proceed further

**Comment by evgenydmitriev** [comment]
🎉 @Hjklvfr submitted the winning pull request and claimed the bounty! Congrats!
