### ISSUE TITLE
Add a Market Manipulations Widget 

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/dn-institute#291]
To participate, submit a pull request that adds a simple and lightweight widget for displaying [Wash Trading and Front Running Metrics](https://rapidapi.com/DNInstitute/api/crypto-market-health/) on the [Market Health Metrics Documentation](https://dn.institute/market-health/docs/market-health-metrics/) page [located here](https://github.com/1712n/dn-institute/blob/main/content/market-health/docs/market-health-metrics.md), and add this issue assignee as a reviewer. Feel free to use whatever JS/TS libraries and frameworks, but keep in mind that your submissions will be evaluated based on the combination of cost/efficiency, security, and load speed. Below is a rough sketch of the widget position on the page, no need to make it look identical:

![widget](https://github.com/1712n/dn-institute/assets/56804873/3551c807-96b7-4d17-9c55-b20850ac84e7)

This time, we offer multiple bounties for the top 3 submissions:

🥇 $1000
🥈 $500
🥉 $250

Anyone can participate and submit their pull request before the deadline. We will also reach to all challenge participants with successful submissions to talk about more permanent research and development opportunities within our projects. Spread the word - additional $250 💰 will be paid for referrals of any winning submissions!

See more details on the [Challenge Program](https://github.com/1712n/dn-institute#-challenge-program) and check out the [success stories](https://www.instagram.com/explore/tags/challenge_successstory/) of the challenge winners. 

Looking forward to your submissions!

**Comment by junowoz** [comment]
Hello. I'm getting several issues with missing files when trying to run Hugo locally. Templates for certain page types and specific shortcodes such as "columns" and "katex" are not being found. Do I have to create those, or are they missing from the repo? Would appreciate any guidance on this. Thanks!

**Comment by evgenydmitriev** [comment]
The website is hosted on GitHub pages attached to this repo. What see you here is what goes into the CI/CD pipeline. You might also want check out the [hugo build action](https://github.com/1712n/dn-institute/blob/main/.github/workflows/hugo.yml) and use our [devcontainer](https://github.com/1712n/dn-institute/tree/main/.devcontainer) if it helps.

**Comment by evgenydmitriev** [comment]
> I'm just trying to determine the most appropriate data to fetch in order to demonstrate the wash trading data. Should we perform some mathematical operations between the values, or can we, for instance, use the volume_distribution_median to represent wash trading data? I was also wondering if we can use the vwap to represent front running.

No need to do any data manipulation at this point. The challenge is about visualizing existing [Wash Trading and Front Running Metrics](https://rapidapi.com/DNInstitute/api/crypto-market-health/) as is.

> should we keep the input scales as they are, or should we apply some weighting to make the chart look better?

You are free to chose whatever scales you want, make them adaptable, or give users additional controls.

> and regarding the chart's time frame, how long should it be? the API provides data for only one week, so should we use labels from monday to sunday?

Feel free to chose whatever looks good to you. As stated in the issue description, the sketch is there to show its position on the page, no need to make it look identical.

**Comment by junowoz** [comment]
> > I'm just trying to determine the most appropriate data to fetch in order to demonstrate the wash trading data. Should we perform some mathematical operations between the values, or can we, for instance, use the volume_distribution_median to represent wash trading data? I was also wondering if we can use the vwap to represent front running.
> 
> No need to do any data manipulation at this point. The challenge is about visualizing existing [Wash Trading and Front Running Metrics](https://rapidapi.com/DNInstitute/api/crypto-market-health/) as is.
> 
> > should we keep the input scales as they are, or should we apply some weighting to make the chart look better?
> 
> You are free to chose whatever scales you want, make them adaptable, or give users additional controls.
> 
> > and regarding the chart's time frame, how long should it be? the API provides data for only one week, so should we use labels from monday to sunday?
> 
> Feel free to choose whatever looks good to you. As stated in the issue description, the sketch is there to show its position on the page, no need to make it look identical.

Thanks! just submitted my PR.

**Comment by Bektur1305** [comment]
Good day.
I have a question regarding 'count_time_distribution' (time of trade).
I didn't find more detailed explanation. 
For example I do have the following data for this indicator:
[7, 8, 79, 29, 24, 60, 35, 20, 13, 14, 32, 19, 19, 5, 12, 6, 9, 8, 2, 14, 22, 16, 12, 3, 6, 11, 3, 3, 6, 6, 18, 17, 4, 1, 9, 17, 37, 9, 10, 34, 11, 39, 66, 28, 28, 26, 315, 36, 0, 0, 0, 0, 0, 0, 0, 2, 4, 5, 2, 4]
What does it mean? Does it mean that such outlier as 315 is anomaly?
Does this indicator has any features?

thx in advance

**Comment by evgenydmitriev** [comment]
This issue is about creating a dynamic widget based on [this Wash Trading and Front Running Metrics API endpoint](https://rapidapi.com/DNInstitute/api/crypto-market-health/) that visualizes returned objects. Feel free to provide your solution to the challenge in a pull request.

**Comment by Bektur1305** [comment]
The challenge has been completed. Could you kindly please have a look? Thanks

**Comment by arlansonic** [comment]
I raised a PR for this activity about 5 days ago and ended up not announcing it here:

Follow the PR link: https://github.com/1712n/dn-institute/pull/303

**Comment by Bektur1305** [comment]
The challenge has been completed. Could you kindly please have a look? Thanks

**Comment by NightSkyHoney** [comment]
thanks for your reply, I will submit my solution.

**Comment by JediFaust** [comment]
@evgenydmitriev Wanted to inform that I faced authorization issues on Metrics API. Tried various methods, however, `invalid session: error finding user for endpoint` error remains. I guess issue is related to MongoDB. Is there possibility to fix it, if the submission acceptance is still active?

**Comment by marina-chibizova** [comment]
@JediFaust yes, it's a problem on our side. I'll fix it today

**Comment by marina-chibizova** [comment]
@JediFaust it's fixed

**Comment by JediFaust** [comment]
@marina-chibizova Thanks!

**Comment by JediFaust** [comment]
@marina-chibizova I reached to some point in submiting a solution. Now I have a two ways to design a widget:
- According to API returned data, there is no metrics as Market Manipulation and Front Running Index. Assuming that no data manipulations needed, I've decided to visualize different indicators from the [docs page](https://dn.institute/market-health/docs/market-health-metrics/) and the current widget is designed [like this](https://jedifaust.github.io/dn-institute/market-health/docs/market-health-metrics/).
- I noticed that returned data contains different metrics from the docs page, and wanted to know how exactly they should look.

**Comment by marina-chibizova** [comment]
@JediFaust all metrics in the new API generally fall under "wash trading metrics" cause they can be used to identify wash trading. but none of them will be specified as manipulation index. The task is to visualize them as they are in the API, so your MVP is fine.

> I noticed that returned data contains different metrics from the docs page

that's true, I'm working on new documentation and we also will add more of the old metrics to the API eventually. I plan to finish the docs tomorrow

**Comment by marina-chibizova** [comment]
@JediFaust I updated the docs

**Comment by JediFaust** [comment]
> @JediFaust I updated the docs

@marina-chibizova Thank you!

**Comment by Hjklvfr** [comment]
@evgenydmitriev I need a review

**Comment by Hjklvfr** [comment]
@evgenydmitriev, I fixed it.

**Comment by Steph-crown** [comment]
This issue specifies a hard deadline of November 25. I want to confirm if I can still work on it now.

**Comment by evgenydmitriev** [comment]
@Steph-crown, we still accept submissions.
