### ISSUE TITLE
Fixes for images UX

### ISSUE THREAD

**Issue by marina-chibizova** [1712n/dn-institute#300]
Problem 1:
- sometimes post contains multiple consecutive images, like [here](https://dn.institute/market-health/posts/huobi-investigation/#metrics-used). Right now they are stacked one after the other taking too much space and not looking good.
- images are not clickable and therefore hard to read (too small)

Fix 1:
Ideally, we would want to have a carousel/gallery view in the cases of several images stacked, so they would look like in Instagram, and users could horizontally swipe through them.

requirements:
- something lightweight, straightforward and hugo native is strongly preferable 
- ability to click on images and open (enlarge) them
- if several images are stacked - have a carousel view, that shows one bigger picture to showcase the chart and allows to click/swipe through all of them
- captions

Problem 2:
[Images inside text](https://github.com/1712n/dn-institute/pull/298/files#diff-1f16c6c2c95224c296f7f3406231e91879388359aa66a15e05ddcdec7079777b) are not rendered anywhere in github (markdown, devmode or codespace), the only way to see them is after the page is added to the website

Fix 2:
Not sure how to deal with it, as far as I know current way of presenting pictures in the text was implemented to be able to make captions formattable (so they look like captions - centered, cursive, etc). This feature should not be lost

**Comment by alxarno** [comment]
ok, that's good variant - https://splidejs.com

**Comment by alxarno** [comment]
@marina-chibizova added gallery and modals with pictures, you can play around [there](https://github.com/1712n/dn-institute/tree/300-fixes-for-images-ux)

**Comment by marina-chibizova** [comment]
looks good. the only thing is images in the carousel are enlarged and cropped in the text view and one can only see the whole picture by click. Could you show them as is? often they do not make sense because of the crop

<img width="481" alt="image" src="https://github.com/1712n/dn-institute/assets/80579198/18cba727-d53c-45f0-8bb2-2a1dc8058cfd">

@sofiasedlova in the carousel the caption is only shown for the last image (I suppose because it was committed this way when the pictures were stacked). Now to have the caption always visible, reporters would need to add it to every image. @alxarno can you confirm?

**Comment by alxarno** [comment]
Fixed crops. About captions yes, or you give it to every image in sequence, or place separate label after sequence.
