### ISSUE TITLE
Improve taxonomies pagination & layout

### ISSUE THREAD

**Issue by marina-chibizova** [1712n/dn-institute#36]
We have more and more contributions to the content and now there is a pagination for custodians, with only 10 per page:
![image](https://github.com/1712n/dni-website/assets/80579198/3fc10640-ce29-4913-8d9d-74df2324e691).

Could you change this number to 50? Is there any way to show the taxonomy other than buttons?

**Comment by marina-chibizova** [comment]
I like Wikipedia alphabetical [taxonomy](https://en.wikipedia.org/w/index.php?title=Category:Wikipedia_how-to&from=R) - not critical now, but we will have much more custodians in the future, so this maybe the way to go. and [this](https://attack.mitre.org/) is our general reference for this project.

**Comment by danisztls** [comment]
ok
