### ISSUE TITLE
Build plagiarism detection bot 

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/dn-institute#424]
Our crowdsourced [Crypto Attack Wiki](https://github.com/1712n/dn-institute/tree/main/content/attacks) has a few [QA bots](https://github.com/1712n/dn-institute/blob/main/.github/workflows/) in charge of automated PR quality checks to follow our [submission guidelines](https://github.com/1712n/dn-institute/issues/277#:~:text=Submission%20Guidelines,-Ensure%20your%20submission).

To participate in the challenge, submit a pull request that refactors an existing bot or creates a new one that adds plagiarism detection and request a review from this issue assignee. You can leverage GitHub Actions or any serverless platform of your choice. All submissions will be reviewed by the maintainers, and additional changes to your pull request may be asked of you to improve code quality, security, and/or efficiency.

Anyone can participate in this challenge. You don't need anyone's approval to try! See more details on the [Challenge Program](https://github.com/1712n/dn-institute#-challenge-program) and check out the [success stories](https://www.instagram.com/explore/tags/challenge_successstory/) of the challenge winners. Looking forward to your submissions!

### How to Claim Bounty
Email your bitcoin or stablecoin payment address to [challenge.bounties@dn.institute](mailto:challenge.bounties@dn.institute) with a link to your merged pull request. Expect all payouts to be completed by the end of the month.

**Comment by kol3x** [comment]
Hi, I am interested in this issue.

Do we want to check the text for plagiarism against existing articles on the platform, or should we include external sources as well? If it's the latter, we could use an external API like [Copyleaks](https://copyleaks.com).

Here is a pricing for it:
![image](https://github.com/1712n/dn-institute/assets/45823609/f7410c2a-ceb5-48a9-ba80-25daddfcadde)

Additionally, do we care to check for AI generated content too?

Let me know what you think.

**Comment by evgenydmitriev** [comment]
@kol3x, the challenge is mostly about catching open web plagiarism - people simply copy-pasting significant portions of the articles from other places. Using 3rd party APIs like Copyleaks is indeed one of the approaches, however it comes with its own implementation challenges and additional costs. Keep this in mind when submitting your solution. There are might be more clever and efficient ways of catching plagiarism.

**Comment by evgenydmitriev** [comment]
🎉 congrats to @kol3x for solving the challenge, getting the bounty, and joining the NLP research team!
