### ISSUE TITLE
Character Count/Cost Automate

### ISSUE THREAD

**Issue by jhirschkorn** [1712n/dn-institute#44]
@danisztls , is there a way we can automate the counting of characters and calculation of costs for submissions after they are approved?

**Comment by danisztls** [comment]
@jhirschkorn Yes. What's the formula? Can have a script that calculate the cost and write it as a comment to a PR or issue. The limitation is that this workflow will not work properly in a branch from a fork as discussed [here](https://github.com/1712n/dni-website/issues/33) so it will either comment to an issue after a merge to main or to a follow up PR after a merge to a pre-production branch.

**Comment by jhirschkorn** [comment]
thanks @danisztls  Basic flow is:
1. After PR is approved by Incas and merged,
2. Calculate payout as 5 cents per character 
3. Ping @albina-at-inca with final payout and the GH name of the original author of the article.

**Comment by albina-at-inca** [comment]
Ok, thank you @danisztls .

**Comment by danisztls** [comment]
Not all PRs qualify because some will be internal and done by us, so payout automation is manually triggered. If this is a nuisance I can try to improve it.

**Comment by albina-at-inca** [comment]
I see.

@danisztls @jhirschkorn can you just make sure to manually trigger /payout every time someone needs to be paid please, so this way I know I need to pay them? Thank you.

**Comment by evgenydmitriev** [comment]
fixed in  #104 and #102
